uncaught FileExistsError: File exists (in copyTree(a, existing_dir))
  dest_existed.chpl:3: thrown here
  dest_existed.chpl:3: uncaught here
