bug: References in tuples don't work like you would expect

The refernce should be placed into the tuple rather than having its value
get captured.
